name: "Modbus <=> MQTT"
description: "Service converts RTU and TCP Modbus to MQTT from other 21"
version: 0.16.25-srv104
url: https://github.com/modbus2mqtt/server/blob/main/introduction.md
webui: http://[HOST]:[PORT:3000]
panel_icon: mdi:arrow-left-right-bold-outline
slug: modbus2mqtt.latest
arch:
  - armv7
  - aarch64
  - amd64
services:
  - mqtt:want
map:
  - share:rw
  - config:rw
  - ssl:rw
hassio_api: true
hassio_role: default
uart: true
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
codenotary: info@carcam360.de
ports:
  3000/tcp: 3000
