name: "Modbus <=> MQTT"
description: "Service converts RTU and TCP Modbus to MQTT from other 21"
version: 0.16.26-srv115
image: ghcr.io/modbus2mqtt/modbus2mqtt.latest
url: https://github.com/modbus2mqtt/server/blob/main/introduction.md
webui: http://[HOST]:[PORT:3000]
panel_icon: mdi:arrow-left-right-bold-outline
slug: modbus2mqtt.latest
arch:
  - aarch64
  - amd64
services:
  - mqtt:want
map:
  - share:rw
  - config:rw
  - ssl:rw
hassio_api: true
hassio_role: default
uart: true
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
ports:
  9229/tcp: null
  502/tcp: null
ports_description:
  9229/tcp: Map node debug port
  502:/tcp: TCP Bridge port
